server:
  port: 8085
  
spring:
  application:
    name: LibraryStatisticsService

eureka:
  client:
    serviceUrl: 
       defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    